use cuda_sys;

use super::Error;

impl Into<cuda_sys::cudaError> for Error {
    fn into(self) -> cuda_sys::cudaError {
        match self {
            Error::MemoryAllocation => cuda_sys::cudaErrorMemoryAllocation,
            Error::InitializationError => cuda_sys::cudaErrorInitializationError,
            Error::LaunchFailure => cuda_sys::cudaErrorLaunchFailure,
            Error::PriorLaunchFailure => cuda_sys::cudaErrorPriorLaunchFailure,
            Error::LaunchTimeout => cuda_sys::cudaErrorLaunchTimeout,
            Error::LaunchOutOfResources => cuda_sys::cudaErrorLaunchOutOfResources,
            Error::InvalidDeviceFunction => cuda_sys::cudaErrorInvalidDeviceFunction,
            Error::InvalidConfiguration => cuda_sys::cudaErrorInvalidConfiguration,
            Error::InvalidDevice => cuda_sys::cudaErrorInvalidDevice,
            Error::InvalidValue => cuda_sys::cudaErrorInvalidValue,
            Error::InvalidPitchValue => cuda_sys::cudaErrorInvalidPitchValue,
            Error::InvalidSymbol => cuda_sys::cudaErrorInvalidSymbol,
            Error::MapBufferObjectFailed => cuda_sys::cudaErrorMapBufferObjectFailed,
            Error::UnmapBufferObjectFailed => cuda_sys::cudaErrorUnmapBufferObjectFailed,
            Error::InvalidHostPointer => cuda_sys::cudaErrorInvalidHostPointer,
            Error::InvalidDevicePointer => cuda_sys::cudaErrorInvalidDevicePointer,
            Error::InvalidTexture => cuda_sys::cudaErrorInvalidTexture,
            Error::InvalidTextureBinding => cuda_sys::cudaErrorInvalidTextureBinding,
            Error::InvalidChannelDescriptor => cuda_sys::cudaErrorInvalidChannelDescriptor,
            Error::InvalidMemcpyDirection => cuda_sys::cudaErrorInvalidMemcpyDirection,
            Error::AddressOfConstant => cuda_sys::cudaErrorAddressOfConstant,
            Error::TextureFetchFailed => cuda_sys::cudaErrorTextureFetchFailed,
            Error::TextureNotBound => cuda_sys::cudaErrorTextureNotBound,
            Error::SynchronizationError => cuda_sys::cudaErrorSynchronizationError,
            Error::InvalidFilterSetting => cuda_sys::cudaErrorInvalidFilterSetting,
            Error::InvalidNormSetting => cuda_sys::cudaErrorInvalidNormSetting,
            Error::MixedDeviceExecution => cuda_sys::cudaErrorMixedDeviceExecution,
            Error::CudartUnloading => cuda_sys::cudaErrorCudartUnloading,
            Error::Unknown => cuda_sys::cudaErrorUnknown,
            Error::NotYetImplemented => cuda_sys::cudaErrorNotYetImplemented,
            Error::MemoryValueTooLarge => cuda_sys::cudaErrorMemoryValueTooLarge,
            Error::InvalidResourceHandle => cuda_sys::cudaErrorInvalidResourceHandle,
            Error::NotReady => cuda_sys::cudaErrorNotReady,
            Error::InsufficientDriver => cuda_sys::cudaErrorInsufficientDriver,
            Error::SetOnActiveProcess => cuda_sys::cudaErrorSetOnActiveProcess,
            Error::InvalidSurface => cuda_sys::cudaErrorInvalidSurface,
            Error::NoDevice => cuda_sys::cudaErrorNoDevice,
            Error::ECCUncorrectable => cuda_sys::cudaErrorECCUncorrectable,
            Error::SharedObjectSymbolNotFound => cuda_sys::cudaErrorSharedObjectSymbolNotFound,
            Error::SharedObjectInitFailed => cuda_sys::cudaErrorSharedObjectInitFailed,
            Error::UnsupportedLimit => cuda_sys::cudaErrorUnsupportedLimit,
            Error::DuplicateVariableName => cuda_sys::cudaErrorDuplicateVariableName,
            Error::DuplicateTextureName => cuda_sys::cudaErrorDuplicateTextureName,
            Error::DuplicateSurfaceName => cuda_sys::cudaErrorDuplicateSurfaceName,
            Error::DevicesUnavailable => cuda_sys::cudaErrorDevicesUnavailable,
            Error::InvalidKernelImage => cuda_sys::cudaErrorInvalidKernelImage,
            Error::NoKernelImageForDevice => cuda_sys::cudaErrorNoKernelImageForDevice,
            Error::IncompatibleDriverContext => cuda_sys::cudaErrorIncompatibleDriverContext,
            Error::PeerAccessAlreadyEnabled => cuda_sys::cudaErrorPeerAccessAlreadyEnabled,
            Error::PeerAccessNotEnabled => cuda_sys::cudaErrorPeerAccessNotEnabled,
            Error::DeviceAlreadyInUse => cuda_sys::cudaErrorDeviceAlreadyInUse,
            Error::ProfilerDisabled => cuda_sys::cudaErrorProfilerDisabled,
            Error::ProfilerNotInitialized => cuda_sys::cudaErrorProfilerNotInitialized,
            Error::ProfilerAlreadyStarted => cuda_sys::cudaErrorProfilerAlreadyStarted,
            Error::ProfilerAlreadyStopped => cuda_sys::cudaErrorProfilerAlreadyStopped,
            Error::Assert => cuda_sys::cudaErrorAssert,
            Error::TooManyPeers => cuda_sys::cudaErrorTooManyPeers,
            Error::HostMemoryAlreadyRegistered => cuda_sys::cudaErrorHostMemoryAlreadyRegistered,
            Error::HostMemoryNotRegistered => cuda_sys::cudaErrorHostMemoryNotRegistered,
            Error::OperatingSystem => cuda_sys::cudaErrorOperatingSystem,
            Error::PeerAccessUnsupported => cuda_sys::cudaErrorPeerAccessUnsupported,
            Error::LaunchMaxDepthExceeded => cuda_sys::cudaErrorLaunchMaxDepthExceeded,
            Error::LaunchFileScopedTex => cuda_sys::cudaErrorLaunchFileScopedTex,
            Error::LaunchFileScopedSurf => cuda_sys::cudaErrorLaunchFileScopedSurf,
            Error::SyncDepthExceeded => cuda_sys::cudaErrorSyncDepthExceeded,
            Error::LaunchPendingCountExceeded => cuda_sys::cudaErrorLaunchPendingCountExceeded,
            Error::NotPermitted => cuda_sys::cudaErrorNotPermitted,
            Error::NotSupported => cuda_sys::cudaErrorNotSupported,
            Error::HardwareStackError => cuda_sys::cudaErrorHardwareStackError,
            Error::IllegalInstruction => cuda_sys::cudaErrorIllegalInstruction,
            Error::MisalignedAddress => cuda_sys::cudaErrorMisalignedAddress,
            Error::InvalidAddressSpace => cuda_sys::cudaErrorInvalidAddressSpace,
            Error::InvalidPc => cuda_sys::cudaErrorInvalidPc,
            Error::IllegalAddress => cuda_sys::cudaErrorIllegalAddress,
            Error::InvalidPtx => cuda_sys::cudaErrorInvalidPtx,
            Error::InvalidGraphicsContext => cuda_sys::cudaErrorInvalidGraphicsContext,
            Error::NvlinkUncorrectable => cuda_sys::cudaErrorNvlinkUncorrectable,
            Error::StartupFailure => cuda_sys::cudaErrorStartupFailure,
        }
    }
}
